Outline
rrrutledge/an-oriole-for-inner-source pull request #1
Opened 2018-05-02 13:12 UTC by rrrutledge

Looking for feedback from @mrsanz and @utanapishtim

2018-05-02 20:44 UTC, mrsanz requested changes
wrong doc for review?

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +The same information in this presentation is also delivered as an O’Reilly Oriole, available freely at https://www.safaribooksonline.com/oriole/.
This seems either premature or not relevant anymore.  Remove all references to the Oriole?

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +In my experience it's been reasonably difficult to share things that are directly usable by other inner source practitioners.
too vague?  What things?  ideas, examples, terminology, challenges, tools?

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +They share their experience in [the InnerSource Commons](http://innersourcecommons.org/) and other public locations.
What other public locations? Is this important?

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +There are many individuals that are excited about inner source.
Not sure that you need a whole sentence to share that individuals are excited, consider combining with the next sentence.

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +The goal of this presentation is to begin to set guildines, structure, and vocabulary for the industry conversation around inner source.
omit "to begin"

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +The goal of this presentation is to begin to set guildines, structure, and vocabulary for the industry conversation around inner source.
for only the industry conversation?  consider omitting "industry"

2018-05-02 20:44 UTC, mrsanz commented on outline.md
> +The goal of this presentation is to begin to set guildines, structure, and vocabulary for the industry conversation around inner source.
Whats the difference between `inner source` and `InnerSource`?

2018-05-02 20:51 UTC, rrrutledge commented on outline.md
> +The same information in this presentation is also delivered as an O’Reilly Oriole, available freely at https://www.safaribooksonline.com/oriole/.
It's [already gone out](http://paypal.github.io/InnerSourceCommons/events/isc-spring-2018-agenda/).  Part of the talk will have to be explaining the switch.  Although I guess there's always the chance to update the abstract (possibly).

2018-05-02 20:52 UTC, rrrutledge commented on outline.md
> +The goal of this presentation is to begin to set guildines, structure, and vocabulary for the industry conversation around inner source.
I used `InnerSource` last year and am using `inner source` this year.

2018-05-02 20:53 UTC, rrrutledge commented
Closing for now as I didn't mean to put this one in review (yet).

2018-05-02 20:53 UTC, closed without merging

2018-05-04 12:43 UTC, rrrutledge commented on outline.md
> +They share their experience in [the InnerSource Commons](http://innersourcecommons.org/) and other public locations.
Blogs.  I think so.

2018-05-04 12:44 UTC, rrrutledge commented on outline.md
> +The goal of this presentation is to begin to set guildines, structure, and vocabulary for the industry conversation around inner source.
`The goal of this presentation is to share guidelines, structure, and vocabulary for the conversation around inner source.`